import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { BatasPembayaran } from "../components/BatasPembayaran";
import { Footer } from "../components/Footer";
import { Iklan } from "../components/Iklan";
import Ombak from "../components/Ombak";
import OmbakFooter from "../components/OmbakFooter";
import style from "../styles/Home.module.css";
import { PelangganType } from "../typings/component";

const Home: NextPage = () => {
  const [input, setInput] = useState<string>("");
  const [pelanggan, setPelanggan] = useState<PelangganType | null>(null);
  const [tidakDitemukan, setTidakDitemukan] = useState<boolean>(false);

  const cari = async () => {
    setTidakDitemukan(false);
    const headers = new Headers();
    headers.append("pragma", "no-cache");
    headers.append("cache-control", "no-cache");

    const payload = {
      method: "GET",
      headers,
    };
    const respon = await fetch(
      "https://api.wisnuaji.my.id/api/v1/search/" + input,
      payload
    );

    const hasil = await respon.json();
    if (!hasil.message) {
      setPelanggan(hasil as PelangganType);
    } else {
      setPelanggan(null);
      setTidakDitemukan(true);
    }
  };
  const tanggalPembayaran = pelanggan
    ? new Date(pelanggan.batasPembayaran).toLocaleDateString().split("/")
    : null;

  return (
    <div className={style.container}>
      <Head>
        <title>INDES</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* bagian atas */}
      <header className={style.header}>
        <div className={style.logo}>
          <Image src="/logo.png" width={60} height={60} alt="logo" />
        </div>
        <h1>Cek Tagihan Pembayaran</h1>
      </header>
      <Ombak />
      {/* ---------------------- */}
      {/* batasan atas */}
      {/* awal inputan id */}
      <div className={style.content}>
        <section className={style.input}>
          <input
            type="search"
            placeholder="masukkan id atau no telp"
            onChange={(e) => {
              setInput(e.target.value);
            }}
            onKeyDown={(e) => {
              if (e.key == "Enter") {
                cari();
              }
            }}
          />
          
          <button onClick={cari}>Cari</button>
        </section>
        <div className={style.input}>
          <input
            type="password"
            placeholder="masukkan passwort"
            onChange={(e) => {
              // setInput(e.target.value);
            }}
            onKeyDown={(e) => {
              if (e.key == "Enter") {
                cari();
              }
            }}
            />
            </div>
        {pelanggan && (
          <div className={style.pelanggan}>
            <div className={style.pelanggan_info}>
              <div className={style.pelanggan_info_header}>Data Pelanggan</div>
              <div className={style.pelanggan_info_pemasangan}>
                <h3>nama</h3>
                <h2>{pelanggan.nama}</h2>
                <h3>tanggal pemasangan</h3>
                <h2>{new Date(pelanggan.pemasangan).toLocaleDateString()}</h2>
              </div>
            </div>

            <div className={style.pelanggan_waktubayar}>
              <h3>Batas Pembayaran Selanjutnya</h3>
              <BatasPembayaran
                isLate={
                  new Date(pelanggan.batasPembayaran).getTime() < Date.now()
                }
                tanggal={pelanggan.batasPembayaran}
              />
              <h3>Tipe langganan</h3>
              <div className={style.pelanggan_waktubayar_paket}>
                paket {pelanggan.paket}
              </div>
            </div>
            <div className={style.pelanggan_tombolbayar}>
              <a
                href={
                  "https://api.wisnuaji.my.id/api/v1/bayar/" + pelanggan._id
                }
                target="_blank"
                rel="noreferrer"
              >
                <button className={style.pelanggan_tombolbayar_bayar}>
                  bayar
                </button>
              </a>
            </div>
          </div>
        )}
        {tidakDitemukan && (
          <div className={style.notfound}>pelanggan tidak ditemukan</div>
        )}
        {/* akhir inputan id */}
        {/* --------------------------- */}
        {/*awal inputan mendaftar pelanggan*/}
        <div style={{padding:"0 20px"}}>
          <p>
            <Link href="/form">belum mendaftar? klik Disini</Link> 
          </p>
        </div>
        {/*akhir inputan mendaftar pelanggan*/}
        {/* --------------------------- */}
        {/* awal iklan */}
        <section>
          <Iklan />
        </section>
        {/* akhir iklan */}
      </div>
      <div className={style.filler} />
      <OmbakFooter />
      {/* footer */}
      <Footer />

      {/* akhir footer */}
    </div>
  );
};

export default Home;
