import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Iklan } from "../components/Iklan";
import Ombak from "../components/Ombak";
import OmbakFooter from "../components/OmbakFooter";
import style from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={style.container}>
      <Head>
        <title>INDES</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* bagian atas */}
      <header className={style.header}>
        <div className={style.logo}>
          <Image src="/logo indes.png" width={60} height={60} />
        </div>
        <h1>Cek Tagihan Pembayaran</h1>
      </header>
      <Ombak />
      {/* ---------------------- */}
      {/* batasan atas */}
      {/* awal inputan id */}
      <div className={style.content}>
        <section className={style.input}>
          <input
            type="search"
            placeholder="silahkan masukkan id atau no telp"
          />
        </section>
        {/* akhir inputan id */}
        {/* --------------------------- */}
        {/* awal iklan */}
        <section>
          <Iklan />
        </section>
        {/* akhir iklan */}
      </div>
      <OmbakFooter />
      {/* footer */}
      <footer>dszyryfutryte</footer>

      {/* akhir footer */}
    </div>
  );
};

export default Home;
